import { useEffect, useState } from 'react'
import { Check, Cloud, Database, FolderOpen, History, KeyRound, LoaderCircle, Save, Sparkles, ArrowUpRight } from 'lucide-react'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import { api, type Project, type ModelResult, type ConnectionSettings, type ConnectionChecks, type SavedIdentity, type SavedProject, type LibraryItem, type LibraryVersion } from './model'

export function Connections({open,onClose}:{open:boolean;onClose:()=>void}){
 const [config,setConfig]=useState<Partial<ConnectionSettings>>({})
 const [values,setValues]=useState({OPENAI_API_KEY:'',OPENAI_MODEL:'gpt-5.6-terra',SUPABASE_URL:'',SUPABASE_SECRET_KEY:''})
 const [checks,setChecks]=useState<ConnectionChecks|null>(null)
 const [busy,setBusy]=useState(false)
 const [error,setError]=useState('')
 useEffect(()=>{if(open){setChecks(null);setError('');api<ConnectionSettings>('/connections').then(c=>{setConfig(c);setValues({OPENAI_API_KEY:'',SUPABASE_SECRET_KEY:'',OPENAI_MODEL:c.openai_model,SUPABASE_URL:c.supabase_url})}).catch(e=>setError(e.message))}},[open])
 async function connect(){
  setBusy(true);setError('')
  try{setConfig(await api<ConnectionSettings>('/connections',values));setValues(v=>({...v,OPENAI_API_KEY:'',SUPABASE_SECRET_KEY:''}));setChecks(await api<ConnectionChecks>('/connections/test',{}))}
  catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 const input=(key:keyof typeof values,label:string,placeholder:string,secret=false)=><label className="connection-field"><span>{label}</span><input type={secret?'password':'text'} autoComplete="off" value={values[key]} placeholder={placeholder} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))} disabled={busy}/></label>
 return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="studio-dialog connection-dialog"><DialogHeader><span className="dialog-symbol"><Cloud size={24}/></span><DialogTitle>Connect your studio</DialogTitle><DialogDescription>Real AI. Real project storage. Your keys stay on this computer, on the server.</DialogDescription></DialogHeader>
 <div className="connection-section"><div className="connection-heading"><Sparkles size={18}/><strong>OpenAI</strong><span>{config.openai_configured?'Key configured':'Not connected'}</span></div>{input('OPENAI_API_KEY','API key',config.openai_configured?'Saved securely · leave blank to keep':'sk-…',true)}{input('OPENAI_MODEL','Model','gpt-5.6-terra')}{checks?.openai&&<div className={'connection-result '+(checks.openai.connected?'passed':'failed')}>{checks.openai.connected&&<Check size={15}/>}<span>{checks.openai.message}{checks.openai.receipt&&<small>{checks.openai.receipt.model} · {checks.openai.receipt.latency_ms} ms · {checks.openai.receipt.request_id}</small>}</span></div>}</div>
 <div className="connection-section"><div className="connection-heading"><Database size={18}/><strong>Supabase</strong><span>{config.supabase_configured?'Project configured':'Not connected'}</span></div>{input('SUPABASE_URL','Project URL','https://your-project.supabase.co')}{input('SUPABASE_SECRET_KEY','Server secret key',config.supabase_configured?'Saved securely · leave blank to keep':'sb_secret_…',true)}{checks?.supabase&&<div className={'connection-result '+(checks.supabase.connected?'passed':'failed')}><span>{checks.supabase.message}</span></div>}<p className="connection-hint">First connection: run this migration in your Supabase SQL Editor. It creates private tables, storage and version history. <a className="inline-link" href="/api/connections/schema" download="prihoda-studio.sql">Download SQL migration ↗</a></p></div>
 {error&&<p className="cloud-error" role="alert">{error}</p>}<button className="primary-button full" disabled={busy} onClick={connect}>{busy?<LoaderCircle size={17} className="spin"/>:<KeyRound size={17}/>} {busy?'Verifying live services…':'Save & verify connections'}</button></DialogContent></Dialog>
}

export function ProjectLibrary({project,model,dirty,busy:parentBusy,canSave,identity,onIdentity,onLoad,capture,onConnect,onNotice}:{project:Project;model:ModelResult;dirty:boolean;busy:boolean;canSave:boolean;identity:SavedIdentity|null;onIdentity:(s:SavedIdentity)=>void;onLoad:(data:SavedProject)=>void;capture:()=>Promise<string>;onConnect:()=>void;onNotice:(text:string)=>void}){
 const [open,setOpen]=useState(false),[saveOpen,setSaveOpen]=useState(false)
 const [items,setItems]=useState<LibraryItem[]>([]),[versions,setVersions]=useState<LibraryVersion[]>([])
 const [selected,setSelected]=useState<LibraryItem|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const [name,setName]=useState(''),[note,setNote]=useState('')
 async function list(){setOpen(true);setBusy(true);setError('');setSelected(null);try{setItems(await api<LibraryItem[]>('/projects'))}catch(e){setItems([]);setError((e as Error).message)}finally{setBusy(false)}}
 async function history(item:LibraryItem){setSelected(item);setBusy(true);setError('');try{setVersions(await api<LibraryVersion[]>('/projects/'+item.id+'/versions'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function load(id:string,version?:number){setBusy(true);setError('');try{const data=await api<SavedProject>('/projects/'+id+(version?'?version='+version:''));onLoad(data);setOpen(false);onNotice('Opened from Supabase · version '+data.version)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function save(){setBusy(true);setError('');try{
  const preview_name=await capture()
  const result=await api<SavedIdentity>('/projects',{project:{...project,project_name:name.trim()||project.project_name},model_id:model.id,project_id:identity?.project_id,expected_version:identity?.latest_version??identity?.version??0,note,preview_name})
  onIdentity(result);setSaveOpen(false);onNotice('Saved to Supabase · '+result.name+' · version '+result.version)
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <><button className="text-button project-library-button" onClick={list} disabled={parentBusy}><FolderOpen size={16}/>Projects</button><button className="outline-button cloud-save" disabled={parentBusy||!canSave||dirty||!(/^[a-f0-9]{20}$|^demo$/.test(model.id))} onClick={()=>{setSaveOpen(true);setName(project.project_name);setNote('');setError('')}}><Save size={15}/>{identity?'Save v'+((identity.latest_version??identity.version)+1):'Save project'}</button>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="studio-dialog library-dialog"><DialogHeader><span className="dialog-symbol"><Database size={24}/></span><DialogTitle>{selected?selected.name:'Your project library'}</DialogTitle><DialogDescription>Saved in Supabase. Every version includes its parameters and original Blender model.</DialogDescription></DialogHeader>
 {busy&&<div className="cloud-loading"><LoaderCircle className="spin" size={20}/>Loading from Supabase…</div>}
 {error&&<div className="cloud-empty"><Cloud size={34}/><p role="alert">{error}</p><button className="outline-button" onClick={()=>{setOpen(false);onConnect()}}>Open connections <ArrowUpRight size={15}/></button></div>}
 {!error&&!busy&&!selected&&!items.length&&<div className="cloud-empty"><FolderOpen size={34}/><h3>Your first concept belongs here.</h3><p>Generate a model, then save it to create your project library.</p></div>}
 {!busy&&!error&&!selected&&<div className="project-list">{items.map(item=><div className="project-card" key={item.id}><span className="project-color" style={{background:item.ducts?.color}}/><button onClick={()=>load(item.id)}><strong>{item.name}</strong><span>{item.room?.length_m} × {item.room?.width_m} × {item.room?.height_m} m · {item.ducts?.count} ducts</span><small>Version {item.latest_version} · {new Date(item.updated_at).toLocaleDateString()}</small></button><button aria-label={'Version history of '+item.name} className="icon-button" onClick={()=>history(item)}><History size={19}/></button></div>)}</div>}
 {!busy&&!error&&selected&&<><button className="inline-link" onClick={()=>setSelected(null)}>← All projects</button><div className="project-list">{versions.map(v=><button className="version-card" onClick={()=>load(selected.id,v.version)} key={v.id}><strong>Version {v.version}</strong><span>{v.note||'Concept snapshot'}</span><small>{new Date(v.created_at).toLocaleString()}</small><ArrowUpRight size={18}/></button>)}</div></>}
 </DialogContent></Dialog>
 <Dialog open={saveOpen} onOpenChange={v=>{if(!busy)setSaveOpen(v)}}><DialogContent className="studio-dialog"><DialogHeader><span className="dialog-symbol"><Save size={24}/></span><DialogTitle>Save a version</DialogTitle><DialogDescription>Parameters, GLB, Blender source and a preview will be uploaded to your private Supabase storage.</DialogDescription></DialogHeader><label className="connection-field"><span>Project name</span><input value={name} maxLength={100} onChange={e=>setName(e.target.value)} disabled={busy}/></label><label className="connection-field"><span>What changed?</span><textarea placeholder="Optional version note…" value={note} maxLength={1000} onChange={e=>setNote(e.target.value)} disabled={busy}/></label>{error&&<p className="cloud-error" role="alert">{error}</p>}<button className="primary-button full" disabled={busy||!name.trim()} onClick={save}>{busy?<LoaderCircle className="spin" size={17}/>:<Database size={17}/>} {busy?'Saving to Supabase…':'Save to Supabase'}</button></DialogContent></Dialog></>
}
